(() => {
  'use strict';
  const N=window.NOVIQ;N.state=N.storage.load();
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=N.util.escape;
  let lastFocus=null,toastTimer=null,busy=false,pendingImport=null;
  const featured=()=>N.matches.find(m=>m.id==='mci-rma')||N.matches[0];
  const activeThesis=()=>N.state.theses.find(t=>t.id===N.state.activeThesisId)||null;
  const stage=()=>!N.state.diagnostic.completed?'diagnostic':!activeThesis()?'briefing':'replay';
  const icon=n=>`<span class="glyph" aria-hidden="true">${({home:'⌂',matches:'◫',ai:'✦',profile:'◎',close:'×',check:'✓',theme:'◐'}[n]||'•')}</span>`;
  const save=()=>N.storage.save();
  function toast(msg){const e=$('#toast');if(!e)return;clearTimeout(toastTimer);e.textContent=msg;e.classList.add('show');toastTimer=setTimeout(()=>e.classList.remove('show'),2400)}
  function appMarkup(){const t=N.t;return `<a class="skip-link" href="#main">${esc(t('skip'))}</a><main id="main" class="app" tabindex="-1">
<header class="topbar"><div class="brand">NOVIQ <span>5.2</span></div><div class="top-actions"><button class="icon-btn" data-action="theme" aria-label="${esc(t('appearance'))}">${icon('theme')}</button><button class="icon-btn" data-action="profile" aria-label="${esc(t('profile'))}">BT</button></div></header>
<section class="screen" data-screen="home"><section class="hero"><p class="kicker">PERSONAL SPORTS INTELLIGENCE</p><div class="hero-grid"><div><h1>${esc(t('hero'))}</h1><p>${esc(t('heroCopy'))}</p></div><div class="iq"><strong id="sportsIq">${N.util.format(N.state.sportsIQ)}</strong><small>SPORTS IQ</small></div></div><button class="primary wide" data-action="continue" data-testid="continue-loop">${esc(t('continue'))}</button></section><div id="journey" class="journey"></div><section class="section"><div class="section-head"><div><p class="kicker">MATCH OF THE DAY</p><h2>${esc(t('today'))}</h2></div><button data-action="matches">${esc(t('allMatches'))}</button></div><div id="featured"></div></section><section class="section"><div class="section-head"><div><p class="kicker">INTELLIGENCE SNAPSHOT</p><h2>${esc(t('snapshot'))}</h2></div></div><div class="insight-grid"><article class="insight"><small>${esc(t('calibration'))}</small><strong>${N.state.calibration.score}%</strong><p>${esc(N.state.patterns[2]?.summary||'')}</p></article><article class="insight"><small>${esc(t('activePattern'))}</small><strong>${N.state.patterns[0]?.confidence||0}%</strong><p>${esc(N.state.patterns[0]?.summary||'')}</p></article></div></section></section>
<section class="screen" data-screen="matches"><div class="section-head"><div><p class="kicker">MATCH CENTER</p><h2>${esc(t('matchCenter'))}</h2></div></div><div class="filters" role="group" aria-label="${esc(t('matchCenter'))}">${[['all',t('all')],['for-you',t('forYou')],['live',t('live')],['replay',t('replay')]].map(([v,l])=>`<button class="filter ${N.state.matchFilter===v?'active':''}" data-filter="${v}" aria-pressed="${N.state.matchFilter===v}">${esc(l)}</button>`).join('')}</div><div id="matchList" class="match-list"></div></section>
<section class="screen" data-screen="ai"><div class="section-head"><div><p class="kicker">AI CORE</p><h2>${esc(t('aiTitle'))}</h2></div></div><article class="card"><p>${esc(t('aiCopy'))}</p><label class="sr-only" for="aiQuestion">${esc(t('aiTitle'))}</label><textarea id="aiQuestion" maxlength="600" placeholder="${esc(t('askPlaceholder'))}"></textarea><span id="aiError" class="field-error"></span><button class="primary wide" data-action="ask">${esc(t('analyze'))}</button><div id="aiResult" aria-live="polite"></div></article></section>
<section class="screen" data-screen="profile"><article class="profile-card"><div class="avatar">BT</div><div><p class="kicker">LOCAL ANALYST</p><h2>${esc(N.state.account.displayName)}</h2><p>${esc(t('local'))}</p></div><div class="stats"><div><strong>${N.util.format(N.state.sportsIQ)}</strong><small>Sports IQ</small></div><div><strong>${N.state.completedLoops}</strong><small>${esc(t('loops'))}</small></div><div><strong>${N.state.replays.length}</strong><small>Replay</small></div></div></article><div class="settings"><button data-action="theme">${esc(t('appearance'))}<b>${N.state.theme}</b></button><button data-action="language">${esc(t('language'))}<b>${N.state.language.toUpperCase()}</b></button><button data-action="export">${esc(t('export'))}<b>JSON</b></button><button data-action="import">${esc(t('import'))}<b>JSON</b></button><button data-action="health">${esc(t('health'))}<b>✓</b></button><button data-action="reset">${esc(t('reset'))}<b>→</b></button></div></section>
<nav class="bottom-nav" aria-label="Primary">${[['home','home'],['matches','matches'],['ai','ai'],['profile','profile']].map(([v,i])=>`<button data-nav="${v}" aria-current="${N.state.activeScreen===v?'page':'false'}">${icon(i)}<span>${esc(N.t(v))}</span></button>`).join('')}</nav>
<div id="modal" class="modal" aria-hidden="true"><div class="backdrop" data-action="close"></div><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><header><h2 id="modalTitle"></h2><button class="icon-btn" data-action="close" aria-label="${esc(t('close'))}">${icon('close')}</button></header><div id="modalBody"></div></section></div><div id="toast" class="toast" role="status" aria-live="polite"></div><div id="updateBar" class="update-bar" hidden><span>${esc(t('updateReady'))}</span><button data-action="reload">${esc(t('reload'))}</button></div></main>`}
  function matchCard(m){return `<article class="match-card"><div class="match-meta"><span>${esc(m.tournament)}</span><span>${esc(m.status)}</span></div><div class="teams"><div><b>${esc(m.home)}</b><small>${esc(m.homeStyle)}</small></div><strong>${esc(m.score||m.time)}</strong><div class="away"><b>${esc(m.away)}</b><small>${esc(m.awayStyle)}</small></div></div><div class="signals">${m.signals.slice(0,3).map(s=>`<p><b>${esc(s[0])}</b> ${esc(s[1])}</p>`).join('')}</div><div class="actions"><button class="secondary" data-action="briefing" data-id="${esc(m.id)}">${esc(N.t('briefing'))}</button><button class="primary" data-action="thesis" data-id="${esc(m.id)}">${esc(N.t('createThesis'))}</button></div></article>`}
  function renderDynamic(){document.documentElement.dataset.theme=N.state.theme;document.documentElement.lang=N.state.language;$('#sportsIq').textContent=N.util.format(N.state.sportsIQ);$('#featured').innerHTML=matchCard(featured());const steps=['diagnostic','briefing','replay'];const current=steps.indexOf(stage());$('#journey').innerHTML=steps.map((s,i)=>`<button class="step ${i===current?'active':''} ${i<current?'done':''}" data-action="stage" data-stage="${s}" ${i>current?'disabled':''}><span>${i<current?'✓':i+1}</span><b>${esc(N.t(s))}</b></button>`).join('');const visible=N.matches.filter(m=>N.state.matchFilter==='all'||m.groups?.includes(N.state.matchFilter));$('#matchList').innerHTML=visible.length?visible.map(m=>`<button class="mini-match" data-action="match" data-id="${esc(m.id)}"><span>${esc(m.home)} — ${esc(m.away)}</span><b>${esc(m.score||m.time)}</b><small>${esc(m.tournament)} · ${esc(m.status)}</small></button>`).join(''):`<div class="empty">${esc(N.t('empty'))}</div>`;show(N.state.activeScreen,false)}
  function show(name,persist=true){N.state.activeScreen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('[data-nav]').forEach(b=>b.setAttribute('aria-current',b.dataset.nav===name?'page':'false'));if(persist)save();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
  function openModal(title,html){lastFocus=document.activeElement;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');$('#main').setAttribute('inert','');$('#modal').removeAttribute('inert');document.body.classList.add('locked');setTimeout(()=>$('#modal .sheet button,#modal .sheet textarea,#modal .sheet input')?.focus(),0)}
  function closeModal(){const m=$('#modal');m.classList.remove('open');m.setAttribute('aria-hidden','true');$('#main').removeAttribute('inert');document.body.classList.remove('locked');if(lastFocus?.isConnected)lastFocus.focus();lastFocus=null}
  async function openBriefing(id){const m=N.matches.find(x=>x.id===id);if(!m)return;try{const b=await N.ai.briefing(m);openModal(`${m.home} — ${m.away}`,`<div class="briefing" data-testid="briefing"><h3>${esc(N.t('facts'))}</h3>${b.facts.map(x=>`<p>✓ ${esc(x)}</p>`).join('')}<h3>${esc(N.t('signals'))}</h3>${b.signals.map(x=>`<p>→ ${esc(x)}</p>`).join('')}<h3>${esc(N.t('unknowns'))}</h3>${b.unknowns.map(x=>`<p>○ ${esc(x)}</p>`).join('')}<div class="chips"><span>${esc(N.t('confidence'))}: ${esc(b.confidence)}</span><span>${esc(N.t('source'))}: ${esc(b.source)}</span></div><button class="primary wide" data-action="thesis" data-id="${esc(id)}">${esc(N.t('createThesis'))}</button></div>`)}catch(error){console.error(error);toast(N.t('error'))}}
  function openThesis(id){const m=N.matches.find(x=>x.id===id);if(!m)return;openModal(N.t('createThesis'),`<form id="thesisForm" data-match-id="${esc(id)}" novalidate><p><b>${esc(m.home)} — ${esc(m.away)}</b></p>${[['scenario','scenario'],['reason','reason'],['risk','risk']].map(([name,key])=>`<label>${esc(N.t(key))}<textarea name="${name}" maxlength="900" aria-describedby="${name}Error"></textarea><span id="${name}Error" class="field-error"></span></label>`).join('')}<label>${esc(N.t('confidence'))}<output id="confOut">65%</output><input name="confidence" type="range" min="30" max="95" value="65"></label><button class="primary wide" type="submit" data-testid="save-thesis">${esc(N.t('save'))}</button></form>`)}
  function saveThesis(form){if(busy)return;const values=['scenario','reason','risk'].map(n=>form.elements[n].value.trim());let valid=true;values.forEach((v,i)=>{const n=['scenario','reason','risk'][i],err=$(`#${n}Error`);err.textContent=v.length>=12?'':N.t('required');if(v.length<12){form.elements[n].focus();valid=false}});if(new Set(values.map(v=>v.toLowerCase())).size<3){$('#riskError').textContent=N.t('duplicate');valid=false}if(!valid)return;busy=true;try{const thesis=N.domain.createThesis({matchId:form.dataset.matchId,scenario:values[0],reason:values[1],risk:values[2],confidence:form.elements.confidence.value});N.state.theses.push(thesis);N.state.activeThesisId=thesis.id;save();closeModal();renderDynamic();toast(N.t('saved'))}finally{busy=false}}
  function openReplay(){const thesis=activeThesis();if(!thesis)return;openModal(N.t('replay'),`<div data-testid="replay"><h3>${esc(N.t('originalDecision'))}</h3><p>${esc(thesis.scenario)}</p><h3>${esc(N.t('declaredRisk'))}</h3><p>${esc(thesis.risk)}</p><label>${esc(N.t('decisionQuality'))}<textarea id="reflection" maxlength="500">Reviewed the evidence, uncertainty, and alternative scenario.</textarea></label><button class="primary wide" data-action="complete-replay" data-id="${esc(thesis.id)}">${esc(N.t('completeReplay'))}</button></div>`)}
  function completeReplay(id){if(busy)return;busy=true;try{N.domain.completeReplay(id,$('#reflection')?.value);save();closeModal();renderDynamic();toast(N.t('replayDone'))}catch(e){toast(e.message==='REPLAY_EXISTS'?N.t('alreadyReplayed'):N.t('error'))}finally{busy=false}}
  function continueLoop(){if(stage()==='diagnostic')openModal(N.t('diagnostic'),`<div data-testid="diagnostic"><p>${esc(N.t('diagnosticQuestion'))}</p>${[55,70,85].map(v=>`<button class="secondary wide" data-action="diagnostic" data-value="${v}">${v}%</button>`).join('')}</div>`);else if(stage()==='briefing')openBriefing(featured().id);else openReplay()}
  async function ask(){const q=$('#aiQuestion').value.trim();if(q.length<4){$('#aiError').textContent=N.t('required');return}$('#aiError').textContent='';$('#aiResult').innerHTML=`<div class="ai-answer">${esc(N.t('loading'))}</div>`;try{const a=await N.ai.ask(q);$('#aiResult').innerHTML=`<div class="ai-answer"><h3>${esc(N.t('conclusion'))}</h3><p>${esc(a.conclusion)}</p><div class="chips"><span>${esc(N.t('confidence'))}: ${esc(a.confidence)}</span><span>${esc(N.t('source'))}: ${esc(a.source)}</span></div><h3>${esc(N.t('alternative'))}</h3><p>${esc(a.alternative)}</p><h3>${esc(N.t('unknowns'))}</h3>${a.unknowns.map(x=>`<p>○ ${esc(x)}</p>`).join('')}</div>`}catch(e){console.error(e);toast(N.t('error'))}}
  function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([N.storage.export()],{type:'application/json'}));a.download=`noviq-${N.config.version}-backup.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function importData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{pendingImport=N.storage.inspect(await f.text());openModal(N.t('restorePreview'),`<div class="summary"><p>Version: ${esc(pendingImport.summary.version)}</p><p>Sports IQ: ${pendingImport.summary.sportsIQ}</p><p>Theses: ${pendingImport.summary.theses}</p><p>Replays: ${pendingImport.summary.replays}</p><button class="primary wide" data-action="confirm-import">${esc(N.t('restore'))}</button></div>`)}catch{toast(N.t('invalidBackup'))}};input.click()}
  function health(){const h=N.health.run();openModal(N.t('health'),`<div><h3>${esc(h.ok?N.t('healthy'):N.t('error'))}</h3>${Object.entries(h.checks).map(([k,v])=>`<p>${v?'✓':'!'} ${esc(k)}</p>`).join('')}</div>`)}
  function onboarding(){if(N.state.onboardingSeen)return;openModal(N.t('onboarding'),`<div class="onboarding" data-testid="onboarding"><p>${esc(N.t('onboardingCopy'))}</p><ol><li>Briefing</li><li>Thesis</li><li>Replay</li></ol><button class="primary wide" data-action="start" data-testid="start-onboarding">${esc(N.t('start'))}</button></div>`)}
  function bind(){document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-nav],[data-filter]');if(!el)return;if(el.dataset.nav)return show(el.dataset.nav);if(el.dataset.filter){N.state.matchFilter=el.dataset.filter;save();renderApp();return}const a=el.dataset.action,id=el.dataset.id;if(a==='theme'){N.state.theme=N.state.theme==='dark'?'light':'dark';save();renderApp()}else if(a==='profile')show('profile');else if(a==='matches')show('matches');else if(a==='continue'||a==='stage')continueLoop();else if(a==='close')closeModal();else if(a==='briefing')openBriefing(id);else if(a==='thesis')openThesis(id);else if(a==='match')openBriefing(id);else if(a==='diagnostic'){N.state.diagnostic={completed:true,answers:[Number(el.dataset.value)],lastAt:N.util.now()};save();closeModal();renderDynamic()}else if(a==='complete-replay')completeReplay(id);else if(a==='ask')ask();else if(a==='language'){N.state.language=({ru:'uk',uk:'en',en:'ru'})[N.state.language];save();renderApp()}else if(a==='export')exportData();else if(a==='import')importData();else if(a==='confirm-import'){localStorage.setItem(N.config.backupKey,JSON.stringify(N.state));N.state=pendingImport.state;N.storage.save({backup:false});pendingImport=null;closeModal();renderApp();toast(N.t('restored'))}else if(a==='health')health();else if(a==='reset')openModal(N.t('resetConfirm'),`<p>${esc(N.t('resetBody'))}</p><div class="actions"><button class="secondary" data-action="close">${esc(N.t('cancel'))}</button><button class="primary" data-action="confirm-reset">${esc(N.t('confirm'))}</button></div>`);else if(a==='confirm-reset'){N.storage.reset();closeModal();renderApp()}else if(a==='start'){N.state.onboardingSeen=true;save();closeModal();continueLoop()}else if(a==='reload')location.reload()});document.addEventListener('submit',e=>{if(e.target.id==='thesisForm'){e.preventDefault();saveThesis(e.target)}});document.addEventListener('input',e=>{if(e.target.name==='confidence')$('#confOut').textContent=`${e.target.value}%`});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modal').classList.contains('open'))closeModal();if(e.key==='Tab'&&$('#modal').classList.contains('open')){const f=$$('#modal button,#modal textarea,#modal input').filter(x=>!x.disabled&&x.offsetParent!==null);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}})}
  function setupPwa(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw-v52.js').then(reg=>{if(reg.waiting)$('#updateBar').hidden=false;reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('#updateBar').hidden=false})})}).catch(console.warn);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!sessionStorage.getItem('noviq-reloaded')){sessionStorage.setItem('noviq-reloaded','1');location.reload()}})}
  function renderApp(){document.body.innerHTML=appMarkup();renderDynamic();onboarding()}
  bind();renderApp();setupPwa();
})();