(() => {
  'use strict';
  const N=window.NOVIQ,$=N.$,$$=N.$$;
  N.openDataStatus=()=>{const s=N.sportsGateway.status();N.openModal({title:'Sports Data Gateway',kicker:'INTEGRATION STATUS',html:`<div class="truth-banner"><b>${s.mode.toUpperCase()} MODE</b><p>Текущая версия честно использует демонстрационный спортивный feed. Реальный provider, серверный AI и push ещё не подключены.</p></div><div class="integration-grid"><div><span>Sports feed</span><b>Demo adapter</b><small>Backend interface ready</small></div><div><span>AI layer</span><b>Local simulation</b><small>Server endpoint ready</small></div><div><span>Authentication</span><b>Guest local</b><small>Supabase-ready schema</small></div><div><span>Notifications</span><b>In-app only</b><small>Push requires service backend</small></div></div><div class="info-card"><h3>Что нужно для production</h3><p>Ключ поставщика данных, серверные edge functions, Supabase project, secrets, rate limits, monitoring и юридически допустимые права на данные.</p></div><div class="info-card"><h3>Принцип доверия</h3><p>NOVIQ не показывает demo-события как реальные и не обещает гарантированную точность прогноза.</p></div>`});};
  N.openNotifications=()=>N.openModal({title:'Умные уведомления',kicker:'NOTIFICATION INTELLIGENCE',html:`<p class="modal-copy">Уведомление должно отражать изменение ценности решения, а не просто возвращать пользователя в приложение.</p>${Object.entries(N.state.notifications).map(([k,v])=>`<button class="setting-row" data-action="toggle-notification" data-notification="${k}"><span class="setting-icon">${v?'●':'○'}</span><span><b>${({briefings:'AI Briefing',lineups:'Стартовые составы',live:'Live Thesis risk',replay:'Decision Replay',weekly:'Weekly Report',patterns:'Новый паттерн'})[k]}</b><small>${v?'Включено':'Выключено'}</small></span><i>›</i></button>`).join('')}<div class="truth-banner"><b>Push status</b><p>В этой статической версии настройки работают локально. Системные push требуют backend и разрешения устройства.</p></div>`});
  N.openMatchPreferences=()=>N.openModal({title:'Команды и турниры',kicker:'PERSONAL MATCH CENTER',html:`<p class="modal-copy">Выбор влияет на Match Center и рекомендации, но не должен вытеснять матчи для развития слабых навыков.</p><div class="preference-list">${['Polissya','Dynamo Kyiv','Manchester City','Real Madrid'].map(x=>`<button class="preference-chip ${(N.state.favorites.teams||[]).includes(x)?'selected':''}" data-action="toggle-favorite" data-favorite-type="teams" data-value="${x}">${x}</button>`).join('')}</div><div class="preference-list">${['Champions League','Ukraine','Club World Cup'].map(x=>`<button class="preference-chip ${(N.state.favorites.tournaments||[]).includes(x)?'selected':''}" data-action="toggle-favorite" data-favorite-type="tournaments" data-value="${x}">${x}</button>`).join('')}</div>`});
  N.openAccount=()=>N.openModal({title:'Account & Cloud Sync',kicker:'ACCOUNT-READY ARCHITECTURE',html:`<div class="account-demo-card"><span>GUEST MODE</span><h3>Прогресс хранится локально</h3><p>Ты можешь тестировать весь Intelligence Loop без регистрации.</p></div><div class="info-card"><h3>Подготовлено для Supabase</h3><p>Auth, profiles, Thesis versions, Replay, Sports Memory, Sports IQ history, notification preferences и Row Level Security.</p></div><div class="form-group"><label>Email · demo only</label><input class="input" id="demoEmail" type="email" placeholder="name@example.com"></div><div class="modal-actions one"><button class="primary-button" data-action="demo-account">Показать готовый flow</button></div><div class="truth-banner"><b>Без ложной регистрации</b><p>Кнопка не создаёт реальный аккаунт, пока Supabase URL и anon key не настроены.</p></div>`});
  N.openAICore=()=>N.openModal({title:'Спроси NOVIQ',kicker:'AI CORE · DEMO',html:`<div class="ai-orb-large"><b>✦</b></div><p class="modal-copy" style="text-align:center">AI ищет пробелы и альтернативы, но не принимает решение вместо пользователя.</p><div class="ai-suggestions"><button class="ai-suggestion" data-action="use-ai-suggestion">Проверь мою уверенность</button><button class="ai-suggestion" data-action="use-ai-suggestion">Покажи похожую ошибку</button><button class="ai-suggestion" data-action="use-ai-suggestion">Где тактический риск?</button></div><textarea class="textarea" id="aiQuestion" placeholder="Спроси о матче, риске или Sports Memory..."></textarea><div class="modal-actions one"><button class="primary-button" data-action="ask-ai">Анализировать →</button></div><div id="aiAnswer"></div>`});
  N.askAI=async()=>{const q=$('#aiQuestion')?.value.trim()||'';if(q.length<4){N.toast('Сформулируй вопрос подробнее');return;}$('#aiAnswer').innerHTML='<div class="loading-card"><i></i><b>Сопоставляю вопрос с Briefing и Sports Memory…</b></div>';const answer=await N.ai.ask(q);$('#aiAnswer').innerHTML=`<div class="review-card success"><h3>NOVIQ AI</h3><p>${answer}</p></div><div class="info-card"><h3>Confidence</h3><p>Demo inference · medium. Реальные источники будут отображаться после серверной интеграции.</p></div>`;};
  N.openIQMethod=()=>N.openModal({title:'Методология Sports IQ V2',kicker:'TRANSPARENCY',html:`<div class="info-card"><h3>Что повышает рейтинг</h3><p>Причинность, независимые аргументы, сложность матча, управление риском, калибровка и конкретный урок после матча.</p></div><div class="info-card"><h3>Что почти не влияет</h3><p>Количество открытий, лайки, случайно угаданный счёт и бессодержательная активность.</p></div><div class="review-card warning"><h3>Evidence confidence</h3><p>Навык не считается подтверждённым при малом числе решений или данных из одного турнира.</p></div>`});
  N.openLoop=()=>{const s=!N.state.diagnostic.completed?'diagnostic':!N.state.thesis?'briefing':!N.state.thesis.locked?'thesis':'live';({diagnostic:N.openDiagnostic,briefing:()=>N.openBriefing('mci-rma'),thesis:()=>N.openThesis('mci-rma'),live:()=>N.openLive(N.state.thesis.matchId)})[s]();};
  N.exportData=()=>{const blob=new Blob([JSON.stringify(N.state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`noviq-1.2-export-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);N.toast('Экспорт подготовлен');};
  N.resetDemo=()=>N.openModal({title:'Сбросить локальный прогресс?',kicker:'DATA CONTROL',html:`<div class="review-card warning"><h3>Будут удалены</h3><p>Диагностика, Thesis, Replay, Sports Memory, миссии и настройки на этом устройстве.</p></div><div class="modal-actions"><button class="secondary-button" data-action="close-modal">Отмена</button><button class="primary-button" data-action="confirm-reset">Сбросить</button></div>`});
  document.addEventListener('click',e=>{
    const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;const id=el.dataset.matchId;
    const handlers={
      'go-home':()=>N.navigate('home'),'open-profile':()=>N.navigate('profile'),'navigate':()=>N.navigate(el.dataset.nav),'go-intelligence':()=>N.navigate('intelligence'),'close-modal':N.closeModal,
      'continue-loop':N.openLoop,'open-diagnostic':N.openDiagnostic,'select-diagnostic':()=>N.selectDiagnostic(el),'submit-diagnostic':N.submitDiagnostic,
      'open-briefing':()=>N.openBriefing(id),'open-thesis':()=>N.openThesis(id),'save-thesis-draft':N.saveThesisDraft,'review-thesis':N.reviewThesis,'edit-thesis':()=>N.openThesis(N.state.thesis?.matchId),'lock-thesis':N.lockThesis,
      'open-live':()=>N.openLive(id),'save-live-note':()=>N.saveLiveNote(id),'open-replay':()=>N.openReplay(id),'complete-replay':()=>N.completeReplay(id),
      'open-calibration':N.openCalibration,'open-pattern':()=>N.openPattern(el.dataset.pattern),'open-mission':N.openMission,'open-weekly-report':N.openWeeklyReport,'open-recommendation':()=>N.openRecommendation(el.dataset.recommendation),'open-recommendations':N.openRecommendations,
      'open-skill':()=>N.openSkill(el.dataset.skill),'open-decision':()=>N.openDecision(el.dataset.decision),'open-lesson':N.openLesson,'answer-lesson':()=>N.answerLesson(el),'complete-lesson':N.completeLesson,
      'open-match-card':()=>N.openMatchCard(id),'open-data-status':N.openDataStatus,'open-notifications':N.openNotifications,'open-match-preferences':N.openMatchPreferences,'open-account':N.openAccount,'open-ai-core':N.openAICore,'ask-ai':N.askAI,'open-iq-method':N.openIQMethod,
      'use-ai-suggestion':()=>{const q=$('#aiQuestion');if(q){q.value=el.textContent.trim();q.focus();}},
      'toggle-notification':()=>{const k=el.dataset.notification;N.state.notifications[k]=!N.state.notifications[k];N.save();N.openNotifications();},
      'toggle-favorite':()=>{const type=el.dataset.favoriteType,value=el.dataset.value,arr=N.state.favorites[type];N.state.favorites[type]=arr.includes(value)?arr.filter(x=>x!==value):[...arr,value];N.save();N.applyState();N.openMatchPreferences();},
      'change-language':()=>N.openModal({title:'Язык',kicker:'LOCALIZATION',html:`<div class="option-grid">${[['ru','Русский'],['ua','Українська'],['en','English']].map(([v,l])=>`<button class="option-button ${N.state.language===v?'selected':''}" data-action="set-language" data-language="${v}">${l}</button>`).join('')}</div><div class="truth-banner"><b>Localization status</b><p>Основная навигация локализуется. Часть аналитического demo-контента пока остаётся на русском.</p></div>`}),
      'set-language':()=>{N.state.language=el.dataset.language;N.save();N.applyState();N.closeModal();N.toast('Язык изменён');},
      'toggle-theme':()=>{N.state.theme=N.state.theme==='dark'?'light':'dark';N.save();N.applyState();N.toast(N.state.theme==='dark'?'Dark Elite':'Light Elite');},
      'export-data':N.exportData,'reset-demo':N.resetDemo,'confirm-reset':()=>{localStorage.removeItem(N.config.storageKey);N.state=N.util.clone(N.defaultState);N.save();N.applyState();N.closeModal();N.toast('Прогресс сброшен');},
      'dispute-pattern':()=>N.toast('Паттерн отмечен для перепроверки'),'memory-filters':()=>N.toast('Фильтры: навык, турнир, команда, confidence'),'demo-account':()=>N.toast('Supabase не настроен: аккаунт не создан'),
      'install-app':async()=>{if(!N.pwa.prompt){N.toast('На iPhone: Поделиться → На экран «Домой»');return;}N.pwa.prompt.prompt();await N.pwa.prompt.userChoice;N.pwa.prompt=null;$('#installBanner').hidden=true;},
      'dismiss-install':()=>{N.state.installDismissed=true;N.save();$('#installBanner').hidden=true;}
    };if(handlers[a])handlers[a]();
  });
  document.addEventListener('click',e=>{
    const mode=e.target.closest('[data-thesis-mode]');if(mode){$('#modalContent').dataset.mode=mode.dataset.thesisMode;$$('[data-thesis-mode]').forEach(b=>b.classList.toggle('selected',b===mode));$$('.expert-only').forEach(x=>x.hidden=mode.dataset.thesisMode==='quick');}
    const outcome=e.target.closest('[data-outcome]');if(outcome){$('#modalContent').dataset.outcome=outcome.dataset.outcome;$$('[data-outcome]').forEach(b=>b.classList.toggle('selected',b===outcome));}
    const source=e.target.closest('[data-source]');if(source){let arr=[];try{arr=JSON.parse($('#modalContent').dataset.sources||'[]')}catch{};arr=arr.includes(source.dataset.source)?arr.filter(x=>x!==source.dataset.source):[...arr,source.dataset.source];$('#modalContent').dataset.sources=JSON.stringify(arr);source.classList.toggle('selected');}
    const filter=e.target.closest('[data-filter]');if(filter){N.ui.filter=filter.dataset.filter;N.state.activeFilter=N.ui.filter;N.save();$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));N.renderMatches();}
    const date=e.target.closest('[data-date]');if(date){N.ui.date=date.dataset.date;N.state.activeDate=N.ui.date;N.save();$$('[data-date]').forEach(b=>b.classList.toggle('active',b===date));N.renderMatches();}
  });
  document.addEventListener('input',e=>{if(e.target.id==='diagnosticConfidence')$('#diagnosticConfidenceValue').textContent=`${e.target.value}%`;if(e.target.id==='confidenceRange')$('#confidenceValue').textContent=`${e.target.value}%`;if(e.target.id==='matchSearch'){N.ui.search=e.target.value;N.renderMatches();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modalLayer').classList.contains('open'))N.closeModal();});
})();
