(() => {
  'use strict';
  const N=window.NOVIQ;
  N.state=N.storage.load();
  const esc=N.util.escape;
  const fmt=N.util.format;
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const featured=()=>N.matches.find(m=>m.id==='mci-rma')||N.matches[0];
  const stage=()=>!N.state.diagnostic.completed?'diagnostic':!N.state.thesis?'briefing':!N.state.thesis.locked?'thesis':'replay';
  const steps=[['diagnostic','Диагностика'],['briefing','Briefing'],['thesis','Thesis'],['replay','Replay']];

  const markup=()=>`<main class="app">
    <header class="topbar"><div class="brand">NOVIQ <span class="version">${esc(N.config.version)}</span></div><div class="top-actions"><button class="icon-btn" data-action="theme" aria-label="Сменить тему">◐</button><button class="icon-btn" data-action="profile" aria-label="Профиль">BT</button></div></header>
    <section class="screen active" data-screen="home">
      <section class="hero"><span class="kicker">PERSONAL SPORTS INTELLIGENCE</span><div class="hero-row"><div><h1>Думай о спорте точнее.</h1><p>Проверь аргументы до матча, зафиксируй решение и пойми ошибку после финального свистка.</p></div><div class="iq"><div><strong>${fmt(N.state.sportsIQ)}</strong><small>SPORTS IQ</small></div></div></div><button class="primary" style="width:100%;margin-top:22px" data-action="continue">Продолжить цикл →</button></section>
      <div class="journey" id="journey">${steps.map(([id,label],i)=>`<button class="step ${stage()===id?'active':''}" data-action="stage" data-stage="${id}"><span>${i+1}</span><b>${label}</b></button>`).join('')}</div>
      <section class="section"><div class="section-head"><div><span class="kicker">MATCH OF THE DAY</span><h2>Главное решение сегодня</h2></div><button data-action="matches">Все матчи</button></div><div id="featured"></div></section>
      <section class="section"><div class="section-head"><div><span class="kicker">INTELLIGENCE SNAPSHOT</span><h2>Что важно сейчас</h2></div></div><div class="insight-grid"><article class="insight"><span class="kicker">CALIBRATION</span><strong>${N.state.calibration.score}%</strong><p>В диапазоне высокой уверенности ты всё ещё переоцениваешь точность.</p></article><article class="insight"><span class="kicker">ACTIVE PATTERN</span><strong>${esc(N.state.patterns[0]?.confidence||0)}%</strong><p>${esc(N.state.patterns[0]?.summary||'Паттерн пока не выявлен.')}</p></article></div></section>
    </section>
    <section class="screen" data-screen="matches"><div class="section-head"><div><span class="kicker">MATCH CENTER</span><h2>Матчи для анализа</h2></div></div><div class="match-list" id="matchesList"></div></section>
    <section class="screen" data-screen="ai"><div class="section-head"><div><span class="kicker">AI CORE</span><h2>Проверь свою мысль</h2></div></div><div class="ai-card"><p style="color:var(--muted)">Локальный AI не выдаёт прогноз за факт. Он ищет слабые аргументы, завышенную уверенность и альтернативные сценарии.</p><textarea class="textarea" id="aiQuestion" placeholder="Например: почему моя уверенность может быть завышена?"></textarea><button class="primary" style="width:100%;margin-top:10px" data-action="ask">Анализировать</button><div id="aiResult"></div></div></section>
    <section class="screen" data-screen="profile"><div class="profile-card"><div class="profile-head"><div class="avatar">BT</div><div><span class="kicker">LOCAL ANALYST</span><h2 style="margin:5px 0">Богдан Тищенко</h2><p style="margin:0;color:var(--muted)">Прогресс хранится на этом устройстве.</p></div></div><div class="stats"><div class="stat"><strong>${fmt(N.state.sportsIQ)}</strong><small>Sports IQ</small></div><div class="stat"><strong>${N.state.completedLoops}</strong><small>Loops</small></div><div class="stat"><strong>${N.state.calibration.score}%</strong><small>Calibration</small></div></div></div><div class="settings"><button class="setting" data-action="theme"><span>Оформление</span><b>${N.state.theme==='dark'?'Dark':'Light'}</b></button><button class="setting" data-action="export"><span>Экспорт данных</span><b>JSON ↓</b></button><button class="setting" data-action="import"><span>Импорт данных</span><b>JSON ↑</b></button><button class="setting" data-action="health"><span>Состояние приложения</span><b>Проверить</b></button><button class="setting" data-action="reset"><span>Сбросить прогресс</span><b style="color:var(--danger)">Сброс</b></button></div></section>
    <nav class="bottom-nav"><button class="nav active" data-nav="home">Главная</button><button class="nav" data-nav="matches">Матчи</button><button class="nav" data-nav="ai">AI</button><button class="nav" data-nav="profile">Профиль</button></nav>
    <div class="modal" id="modal"><div class="backdrop" data-action="close"></div><section class="sheet"><div class="sheet-head"><div><span class="kicker" id="modalKicker">NOVIQ</span><h2 id="modalTitle"></h2></div><button class="icon-btn" data-action="close">×</button></div><div id="modalBody"></div></section></div>
  </main>`;

  const renderFeatured=()=>{
    const m=featured();
    $('#featured').innerHTML=`<article class="match-card"><div class="match-meta"><span>${esc(m.tournament)}</span><span>IQ VALUE ${esc(m.intelligence)}</span></div><div class="teams"><div class="team"><span class="crest">${esc(m.hc)}</span><b>${esc(m.home)}</b><small>${esc(m.homeStyle)}</small></div><div class="score"><strong>${esc(m.score||m.time)}</strong><small>${esc(m.status)}</small></div><div class="team away"><span class="crest">${esc(m.ac)}</span><b>${esc(m.away)}</b><small>${esc(m.awayStyle)}</small></div></div><div class="signals">${m.signals.slice(0,2).map(s=>`<div class="signal"><b>${esc(s[0])}</b> ${esc(s[1])}</div>`).join('')}</div><div class="actions"><button class="secondary" data-action="briefing" data-id="${esc(m.id)}">AI Briefing</button><button class="primary" data-action="thesis" data-id="${esc(m.id)}">Создать Thesis</button></div></article>`;
  };
  const renderMatches=()=>{$('#matchesList').innerHTML=N.matches.map(m=>`<button class="mini-match" data-action="match" data-id="${esc(m.id)}"><div class="row"><b>${esc(m.home)} — ${esc(m.away)}</b><strong>${esc(m.score||m.time)}</strong></div><div class="row"><small>${esc(m.tournament)}</small><small>${esc(m.status)}</small></div></button>`).join('')};
  const show=(name)=>{$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'})};
  const modal=(title,html,kicker='NOVIQ INTELLIGENCE')=>{$('#modalTitle').textContent=title;$('#modalKicker').textContent=kicker;$('#modalBody').innerHTML=html;$('#modal').classList.add('open')};
  const close=()=>$('#modal').classList.remove('open');
  const openBriefing=async(id)=>{const m=N.matches.find(x=>x.id===id);const b=await N.ai.briefing(m);modal(`${m.home} — ${m.away}`,`<div class="ai-card"><span class="kicker">WHAT WE KNOW</span><div class="evidence">${b.facts.map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><span class="kicker" style="display:block;margin-top:18px">WHAT MAY MATTER</span><div class="evidence">${b.signals.map(x=>`<span>→ ${esc(x)}</span>`).join('')}</div><span class="kicker" style="display:block;margin-top:18px">UNKNOWN</span><div class="evidence">${b.unknowns.map(x=>`<span>○ ${esc(x)}</span>`).join('')}</div><button class="primary" style="width:100%;margin-top:18px" data-action="thesis" data-id="${esc(id)}">Создать Thesis</button></div>`,'AI BRIEFING')};
  const openThesis=(id)=>{const m=N.matches.find(x=>x.id===id);modal('Создать Match Thesis',`<div class="ai-card"><p><b>${esc(m.home)} — ${esc(m.away)}</b></p><textarea class="textarea" id="scenario" placeholder="Как будет развиваться матч?"></textarea><textarea class="textarea" id="reason" style="margin-top:8px" placeholder="Почему ты так думаешь?"></textarea><textarea class="textarea" id="risk" style="margin-top:8px" placeholder="Что может сделать гипотезу неверной?"></textarea><label style="display:block;margin:14px 0 6px">Уверенность <b id="confValue">65%</b></label><input id="confidence" type="range" min="30" max="95" value="65" style="width:100%"><button class="primary" style="width:100%;margin-top:16px" data-action="save-thesis" data-id="${esc(id)}">Зафиксировать решение</button></div>`,'MATCH THESIS')};
  const saveThesis=(id)=>{const scenario=$('#scenario')?.value.trim(),reason=$('#reason')?.value.trim(),risk=$('#risk')?.value.trim();if(!scenario||!reason||!risk){alert('Заполни сценарий, аргумент и риск.');return;}N.state.thesis={matchId:id,scenario,reason,risk,confidence:Number($('#confidence').value),locked:true,createdAt:new Date().toISOString()};N.storage.save();close();document.body.innerHTML=markup();boot();};
  const openMatch=(id)=>{const m=N.matches.find(x=>x.id===id);modal(`${m.home} — ${m.away}`,`<div class="match-card"><div class="match-meta"><span>${esc(m.tournament)}</span><span>${esc(m.status)}</span></div><div class="signals">${m.signals.map(s=>`<div class="signal"><b>${esc(s[0])}</b> ${esc(s[1])}</div>`).join('')}</div><div class="actions"><button class="secondary" data-action="briefing" data-id="${esc(id)}">Briefing</button><button class="primary" data-action="thesis" data-id="${esc(id)}">Thesis</button></div></div>`)};
  const continueLoop=()=>{const s=stage();if(s==='diagnostic')modal('Быстрая диагностика',`<div class="ai-card"><p>Насколько уверенно ты обычно оцениваешь матч до стартовых составов?</p><button class="secondary" style="width:100%;margin-bottom:8px" data-action="diagnostic" data-value="55">Осторожно · 55%</button><button class="secondary" style="width:100%;margin-bottom:8px" data-action="diagnostic" data-value="70">Умеренно · 70%</button><button class="secondary" style="width:100%" data-action="diagnostic" data-value="85">Высоко · 85%</button></div>`,'STARTING POINT');else if(s==='briefing')openBriefing(featured().id);else if(s==='thesis')openThesis(featured().id);else modal('Decision Replay',`<div class="ai-card"><p><b>Твоя гипотеза:</b> ${esc(N.state.thesis.scenario)}</p><p><b>Риск:</b> ${esc(N.state.thesis.risk)}</p><p>После матча сравни исходную логику с результатом. Ценность — в качестве решения, а не в случайном угадывании.</p><button class="primary" style="width:100%" data-action="complete-replay">Завершить Replay</button></div>`,'DECISION REPLAY')};
  const ask=async()=>{const q=$('#aiQuestion').value.trim();if(q.length<4)return;$('#aiResult').innerHTML='<div class="ai-answer">Анализирую аргументы…</div>';const a=await N.ai.ask(q);$('#aiResult').innerHTML=`<div class="ai-answer"><b>Вывод</b><p>${esc(typeof a==='string'?a:a.answer)}</p><div class="evidence"><span>Confidence: medium</span><span>Source: offline rules engine</span><span>Unknowns are not treated as facts</span></div></div>`};
  const exportData=()=>{const blob=new Blob([N.storage.export()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`noviq-${N.config.version}-backup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  const importData=()=>{const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{N.storage.import(await i.files[0].text());location.reload()}catch{alert('Некорректный файл NOVIQ')}};i.click()};
  const onboarding=()=>{if(N.state.onboarding?.completed)return;document.body.insertAdjacentHTML('beforeend',`<div class="onboarding"><section class="onboarding-card"><span class="kicker">NOVIQ ${esc(N.config.version)}</span><h1>Не угадывай. Учись принимать решения.</h1><p style="color:var(--muted)">Один короткий цикл превращает просмотр матча в тренировку спортивного мышления.</p><div class="onboarding-list"><div class="onboarding-item"><b>1. Briefing</b><small>Отдели факты от неизвестного.</small></div><div class="onboarding-item"><b>2. Thesis</b><small>Зафиксируй сценарий и риск.</small></div><div class="onboarding-item"><b>3. Replay</b><small>Разбери качество решения после матча.</small></div></div><button class="primary" style="width:100%" data-action="start">Начать</button></section></div>`)};
  function bind(){document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-nav]');if(!el)return;if(el.dataset.nav)return show(el.dataset.nav);const a=el.dataset.action,id=el.dataset.id;if(a==='theme'){N.state.theme=N.state.theme==='dark'?'light':'dark';N.storage.save();document.documentElement.dataset.theme=N.state.theme}else if(a==='profile')show('profile');else if(a==='matches')show('matches');else if(a==='close')close();else if(a==='briefing')openBriefing(id);else if(a==='thesis')openThesis(id);else if(a==='save-thesis')saveThesis(id);else if(a==='match')openMatch(id);else if(a==='continue')continueLoop();else if(a==='stage')continueLoop();else if(a==='ask')ask();else if(a==='diagnostic'){N.state.diagnostic={completed:true,answers:[Number(el.dataset.value)],lastAt:new Date().toISOString()};N.storage.save();close();location.reload()}else if(a==='complete-replay'){N.state.completedLoops+=1;N.state.sportsIQ+=24;N.state.thesis=null;N.storage.save();close();location.reload()}else if(a==='export')exportData();else if(a==='import')importData();else if(a==='health'){const h=N.health.run();modal('Состояние приложения',`<div class="ai-card"><h3>${h.ok?'Все системы готовы':'Нужна проверка'}</h3>${Object.entries(h.checks).map(([k,v])=>`<p>${v?'✓':'!'} ${esc(k)}</p>`).join('')}</div>`,'LOCAL HEALTH')}else if(a==='reset'){if(confirm('Удалить локальный прогресс?')){N.storage.reset();location.reload()}}else if(a==='start'){N.state.onboarding={completed:true,completedAt:new Date().toISOString()};N.storage.save();$('.onboarding')?.remove();continueLoop()}});document.addEventListener('input',e=>{if(e.target.id==='confidence')$('#confValue').textContent=`${e.target.value}%`})}
  function boot(){document.documentElement.dataset.theme=N.state.theme;renderFeatured();renderMatches();bind();onboarding();N.pwa.init()}
  document.body.innerHTML=markup();boot();
})();