(() => {
  'use strict';
  const N=window.NOVIQ;
  N.state=N.storage.load();
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=N.util.escape, fmt=N.util.format;
  let lastFocus=null, toastTimer=null, matchFilter='all', bound=false;

  const copy={
    ru:{home:'Главная',matches:'Матчи',ai:'AI',profile:'Профиль',hero:'Думай о спорте точнее.',heroCopy:'Проверь аргументы до матча, зафиксируй решение и пойми ошибку после финального свистка.',continue:'Продолжить цикл',today:'Главное решение сегодня',allMatches:'Все матчи',snapshot:'Что важно сейчас',matchCenter:'Матчи для анализа',aiTitle:'Проверь свою мысль',aiCopy:'Локальный AI ищет слабые аргументы, завышенную уверенность и альтернативные сценарии. Он не выдаёт прогноз за факт.',askPlaceholder:'Например: почему моя уверенность может быть завышена?',analyze:'Анализировать',local:'Прогресс хранится на этом устройстве.',theme:'Оформление',language:'Язык',export:'Экспорт данных',import:'Импорт данных',health:'Состояние приложения',reset:'Сбросить прогресс',briefing:'AI Briefing',thesis:'Создать Thesis',diagnostic:'Диагностика',replay:'Replay',facts:'Что известно',signals:'Что может быть важно',unknowns:'Что неизвестно',save:'Зафиксировать решение',scenario:'Как будет развиваться матч?',reason:'Почему ты так думаешь?',risk:'Что может сделать гипотезу неверной?',confidence:'Уверенность',required:'Заполни это поле содержательно.',saved:'Решение зафиксировано',replayDone:'Replay завершён. Sports IQ обновлён.',invalidBackup:'Файл не является резервной копией NOVIQ.',restored:'Данные восстановлены.',healthy:'Приложение работает корректно.',start:'Начать',onboarding:'Не угадывай. Учись принимать решения.',onboardingCopy:'Один короткий цикл превращает просмотр матча в тренировку спортивного мышления.',resetConfirm:'Удалить локальный прогресс?',cancel:'Отмена',confirm:'Удалить'},
    ua:{home:'Головна',matches:'Матчі',ai:'AI',profile:'Профіль',hero:'Думай про спорт точніше.',heroCopy:'Перевір аргументи до матчу, зафіксуй рішення та зрозумій помилку після фінального свистка.',continue:'Продовжити цикл',today:'Головне рішення сьогодні',allMatches:'Усі матчі',snapshot:'Що важливо зараз',matchCenter:'Матчі для аналізу',aiTitle:'Перевір свою думку',aiCopy:'Локальний AI шукає слабкі аргументи, завищену впевненість та альтернативні сценарії. Він не видає прогноз за факт.',askPlaceholder:'Наприклад: чому моя впевненість може бути завищена?',analyze:'Аналізувати',local:'Прогрес зберігається на цьому пристрої.',theme:'Оформлення',language:'Мова',export:'Експорт даних',import:'Імпорт даних',health:'Стан застосунку',reset:'Скинути прогрес',briefing:'AI Briefing',thesis:'Створити Thesis',diagnostic:'Діагностика',replay:'Replay',facts:'Що відомо',signals:'Що може бути важливо',unknowns:'Що невідомо',save:'Зафіксувати рішення',scenario:'Як розвиватиметься матч?',reason:'Чому ти так думаєш?',risk:'Що може зробити гіпотезу хибною?',confidence:'Впевненість',required:'Заповни це поле змістовно.',saved:'Рішення зафіксовано',replayDone:'Replay завершено. Sports IQ оновлено.',invalidBackup:'Файл не є резервною копією NOVIQ.',restored:'Дані відновлено.',healthy:'Застосунок працює коректно.',start:'Почати',onboarding:'Не вгадуй. Вчися приймати рішення.',onboardingCopy:'Один короткий цикл перетворює перегляд матчу на тренування спортивного мислення.',resetConfirm:'Видалити локальний прогрес?',cancel:'Скасувати',confirm:'Видалити'},
    en:{home:'Home',matches:'Matches',ai:'AI',profile:'Profile',hero:'Think about sport more clearly.',heroCopy:'Test your reasoning before the match, lock the decision, and review the mistake after the final whistle.',continue:'Continue loop',today:"Today's key decision",allMatches:'All matches',snapshot:'What matters now',matchCenter:'Matches to analyze',aiTitle:'Challenge your thinking',aiCopy:'Local AI looks for weak evidence, overconfidence, and alternative scenarios. It never presents a prediction as fact.',askPlaceholder:'For example: why might my confidence be too high?',analyze:'Analyze',local:'Progress is stored on this device.',theme:'Appearance',language:'Language',export:'Export data',import:'Import data',health:'App health',reset:'Reset progress',briefing:'AI Briefing',thesis:'Create Thesis',diagnostic:'Diagnostic',replay:'Replay',facts:'What we know',signals:'What may matter',unknowns:'What remains unknown',save:'Lock decision',scenario:'How will the match develop?',reason:'Why do you think so?',risk:'What could make the thesis wrong?',confidence:'Confidence',required:'Add a meaningful answer.',saved:'Decision locked',replayDone:'Replay completed. Sports IQ updated.',invalidBackup:'This is not a valid NOVIQ backup.',restored:'Data restored.',healthy:'The app is healthy.',start:'Start',onboarding:'Do not guess. Learn to decide.',onboardingCopy:'One short loop turns watching a match into sports-thinking practice.',resetConfirm:'Delete local progress?',cancel:'Cancel',confirm:'Delete'}
  };
  const t=k=>(copy[N.state.language]||copy.ru)[k]||k;
  const icon=name=>{const paths={home:'<path d="M3 11.5 10 5l7 6.5V18H6v-6.5Z"/><path d="M8.5 18v-4h3v4"/>',matches:'<rect x="3" y="4" width="14" height="13" rx="3"/><path d="M3 8h14M7 2v4m6-4v4"/>',ai:'<path d="m10 2 1.4 4.1L15.5 7.5l-4.1 1.4L10 13l-1.4-4.1-4.1-1.4 4.1-1.4L10 2Z"/><path d="m15.5 12 .8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2Z"/>',profile:'<circle cx="10" cy="7" r="3"/><path d="M4 18c.5-4 2.5-6 6-6s5.5 2 6 6"/>',theme:'<path d="M14.5 14.5A7 7 0 0 1 6 5.5 7 7 0 1 0 14.5 14.5Z"/>',globe:'<circle cx="10" cy="10" r="7"/><path d="M3 10h14M10 3c2 2 2 12 0 14M10 3c-2 2-2 12 0 14"/>',download:'<path d="M10 3v9m-3-3 3 3 3-3M4 16h12"/>',upload:'<path d="M10 12V3m-3 3 3-3 3 3M4 16h12"/>',heart:'<path d="M10 17s-6-3.7-6-8a3.5 3.5 0 0 1 6-2.4A3.5 3.5 0 0 1 16 9c0 4.3-6 8-6 8Z"/>',trash:'<path d="M4 6h12M8 6V4h4v2m-6 0 1 11h6l1-11M9 9v5m2-5v5"/>',check:'<path d="m4 10 4 4 8-8"/>',close:'<path d="m5 5 10 10M15 5 5 15"/>',arrow:'<path d="M4 10h12m-4-4 4 4-4 4"/>',target:'<circle cx="10" cy="10" r="7"/><circle cx="10" cy="10" r="3"/>',chart:'<path d="M4 17V9m4 8V5m4 12v-7m4 7V3"/>'};return `<svg class="icon" viewBox="0 0 20 20" aria-hidden="true">${paths[name]||paths.target}</svg>`};
  const featured=()=>N.matches.find(m=>m.id==='mci-rma')||N.matches[0];
  const stage=()=>!N.state.diagnostic.completed?'diagnostic':!N.state.thesis?'briefing':!N.state.thesis.locked?'thesis':'replay';
  const rank={diagnostic:0,briefing:1,thesis:2,replay:3};

  const markup=()=>`<a class="skip-link" href="#main-content">Skip to content</a><main class="app" id="main-content" tabindex="-1">
  <header class="topbar"><div class="brand">NOVIQ <span class="version">${esc(N.config.version)}</span></div><div class="top-actions"><button class="icon-btn" data-action="theme" aria-label="${esc(t('theme'))}">${icon('theme')}</button><button class="icon-btn" data-action="profile" aria-label="${esc(t('profile'))}">BT</button></div></header>
  <section class="screen active" data-screen="home" aria-labelledby="home-title"><section class="hero"><span class="kicker">PERSONAL SPORTS INTELLIGENCE</span><div class="hero-row"><div><h1 id="home-title">${esc(t('hero'))}</h1><p>${esc(t('heroCopy'))}</p></div><div class="iq"><div><strong id="sportsIq">${fmt(N.state.sportsIQ)}</strong><small>SPORTS IQ</small></div></div></div><button class="primary wide" data-action="continue" data-testid="continue-loop">${esc(t('continue'))} ${icon('arrow')}</button></section><div class="journey" id="journey"></div><section class="section"><div class="section-head"><div><span class="kicker">MATCH OF THE DAY</span><h2>${esc(t('today'))}</h2></div><button data-action="matches">${esc(t('allMatches'))}</button></div><div id="featured"></div></section><section class="section"><div class="section-head"><div><span class="kicker">INTELLIGENCE SNAPSHOT</span><h2>${esc(t('snapshot'))}</h2></div></div><div class="insight-grid"><article class="insight"><span class="kicker">CALIBRATION</span><strong>${N.state.calibration.score}%</strong><p>${esc(N.state.patterns[2]?.summary||'')}</p></article><article class="insight"><span class="kicker">ACTIVE PATTERN</span><strong>${esc(N.state.patterns[0]?.confidence||0)}%</strong><p>${esc(N.state.patterns[0]?.summary||'')}</p></article></div></section></section>
  <section class="screen" data-screen="matches" aria-labelledby="matches-title"><div class="section-head"><div><span class="kicker">MATCH CENTER</span><h2 id="matches-title">${esc(t('matchCenter'))}</h2></div></div><div class="match-toolbar" role="group" aria-label="Match filters"><button class="filter-chip active" data-filter="all">All</button><button class="filter-chip" data-filter="for-you">For you</button><button class="filter-chip" data-filter="live">Live</button><button class="filter-chip" data-filter="replay">Replay</button></div><div class="match-list" id="matchesList"></div></section>
  <section class="screen" data-screen="ai" aria-labelledby="ai-title"><div class="section-head"><div><span class="kicker">AI CORE</span><h2 id="ai-title">${esc(t('aiTitle'))}</h2></div></div><div class="ai-shell"><div class="ai-card"><div class="ai-orb">${icon('ai')}</div><p>${esc(t('aiCopy'))}</p><div class="field"><label for="aiQuestion" class="sr-only">Question</label><textarea class="textarea" id="aiQuestion" placeholder="${esc(t('askPlaceholder'))}"></textarea><span class="field-error" id="aiError"></span></div><button class="primary wide" data-action="ask">${esc(t('analyze'))}</button><div id="aiResult" aria-live="polite"></div></div></div></section>
  <section class="screen" data-screen="profile" aria-labelledby="profile-title"><div class="profile-card"><div class="profile-head"><div class="avatar">BT</div><div><span class="kicker">LOCAL ANALYST</span><h2 id="profile-title">${esc(N.state.account.displayName||'Богдан Тищенко')}</h2><p>${esc(t('local'))}</p></div></div><div class="stats"><div class="stat"><strong>${fmt(N.state.sportsIQ)}</strong><small>Sports IQ</small></div><div class="stat"><strong>${N.state.completedLoops}</strong><small>Loops</small></div><div class="stat"><strong>${N.state.calibration.score}%</strong><small>Calibration</small></div></div></div><div class="settings"><button class="setting" data-action="theme"><span class="setting-left"><span class="setting-icon">${icon('theme')}</span>${esc(t('theme'))}</span><b>${N.state.theme==='dark'?'Dark':'Light'}</b></button><button class="setting" data-action="language"><span class="setting-left"><span class="setting-icon">${icon('globe')}</span>${esc(t('language'))}</span><b>${N.state.language.toUpperCase()}</b></button><button class="setting" data-action="export"><span class="setting-left"><span class="setting-icon">${icon('download')}</span>${esc(t('export'))}</span><b>JSON</b></button><button class="setting" data-action="import"><span class="setting-left"><span class="setting-icon">${icon('upload')}</span>${esc(t('import'))}</span><b>JSON</b></button><button class="setting" data-action="health"><span class="setting-left"><span class="setting-icon">${icon('heart')}</span>${esc(t('health'))}</span><b>${icon('check')}</b></button><button class="setting" data-action="reset"><span class="setting-left"><span class="setting-icon">${icon('trash')}</span>${esc(t('reset'))}</span><b>→</b></button></div></section>
  <nav class="bottom-nav" aria-label="Primary navigation"><button class="nav active" data-nav="home">${icon('home')}<span>${esc(t('home'))}</span></button><button class="nav" data-nav="matches">${icon('matches')}<span>${esc(t('matches'))}</span></button><button class="nav" data-nav="ai">${icon('ai')}<span>${esc(t('ai'))}</span></button><button class="nav" data-nav="profile">${icon('profile')}<span>${esc(t('profile'))}</span></button></nav>
  <div class="modal" id="modal" aria-hidden="true"><button class="backdrop" data-action="close" aria-label="Close dialog"></button><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="sheet-head"><div><span class="kicker" id="modalKicker">NOVIQ</span><h2 id="modalTitle"></h2></div><button class="icon-btn" data-action="close" aria-label="Close">${icon('close')}</button></div><div id="modalBody"></div></section></div><div class="toast" id="toast" role="status" aria-live="polite"></div></main>`;

  function toast(message){const el=$('#toast');clearTimeout(toastTimer);el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
  function save(){N.state.version=N.config.version;N.storage.save()}
  function renderJourney(){const current=rank[stage()];const labels={diagnostic:t('diagnostic'),briefing:'Briefing',thesis:'Thesis',replay:t('replay')};$('#journey').innerHTML=Object.keys(rank).map((id,i)=>`<button class="step ${i===current?'active':''} ${i<current?'done':''}" data-action="stage" data-stage="${id}" ${i>current?'aria-disabled="true"':''}><span>${i<current?icon('check'):i+1}</span><b>${esc(labels[id])}</b></button>`).join('')}
  function matchCard(m,featuredCard=false){return `<article class="match-card ${featuredCard?'featured':''}"><div class="match-meta"><span>${esc(m.tournament)}</span><span>IQ VALUE ${esc(m.intelligence)}</span></div><div class="teams"><div class="team"><span class="crest" aria-label="${esc(m.home)}">${esc(m.hc)}</span><b>${esc(m.home)}</b><small>${esc(m.homeStyle)}</small></div><div class="score"><strong>${esc(m.score||m.time)}</strong><small>${esc(m.status)}</small></div><div class="team away"><span class="crest" aria-label="${esc(m.away)}">${esc(m.ac)}</span><b>${esc(m.away)}</b><small>${esc(m.awayStyle)}</small></div></div><div class="signals">${m.signals.slice(0,featuredCard?3:2).map(s=>`<div class="signal"><b>${esc(s[0])}</b> ${esc(s[1])}</div>`).join('')}</div><div class="actions"><button class="secondary" data-action="briefing" data-id="${esc(m.id)}">${esc(t('briefing'))}</button><button class="primary" data-action="thesis" data-id="${esc(m.id)}">${esc(t('thesis'))}</button></div></article>`}
  function renderFeatured(){$('#featured').innerHTML=matchCard(featured(),true)}
  function renderMatches(){const visible=N.matches.filter(m=>matchFilter==='all'||m.groups?.includes(matchFilter));$('#matchesList').innerHTML=visible.length?visible.map(m=>`<button class="mini-match" data-action="match" data-id="${esc(m.id)}"><div class="row"><b>${esc(m.home)} — ${esc(m.away)}</b><strong>${esc(m.score||m.time)}</strong></div><div class="row"><small>${esc(m.tournament)}</small><small>${esc(m.status)}</small></div></button>`).join(''):`<div class="empty">No matches in this view.</div>`}
  function show(name){N.state.activeScreen=name;save();$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.nav').forEach(x=>{const on=x.dataset.nav===name;x.classList.toggle('active',on);x.setAttribute('aria-current',on?'page':'false')});window.scrollTo({top:0,behavior:'smooth'})}
  function openModal(title,html,kicker='NOVIQ INTELLIGENCE'){lastFocus=document.activeElement;$('#modalTitle').textContent=title;$('#modalKicker').textContent=kicker;$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('#modalBody button,#modalBody textarea,#modalBody input')?.focus(),30)}
  function closeModal(){const modal=$('#modal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus();lastFocus=null}
  function renderDynamic(){document.documentElement.dataset.theme=N.state.theme;document.documentElement.lang=N.state.language==='ua'?'uk':N.state.language;renderJourney();renderFeatured();renderMatches();$('#sportsIq').textContent=fmt(N.state.sportsIQ)}

  async function openBriefing(id){const m=N.matches.find(x=>x.id===id);if(!m)return;const b=await N.ai.briefing(m);openModal(`${m.home} — ${m.away}`,`<div class="ai-card" data-testid="briefing"><span class="kicker">${esc(t('facts'))}</span><div class="evidence">${b.facts.map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><span class="kicker">${esc(t('signals'))}</span><div class="evidence">${b.signals.map(x=>`<span>→ ${esc(x)}</span>`).join('')}</div><span class="kicker">${esc(t('unknowns'))}</span><div class="evidence">${b.unknowns.map(x=>`<span>○ ${esc(x)}</span>`).join('')}</div><div class="answer-grid"><div class="answer-chip">Confidence<br><b>${esc(b.confidence||'medium')}</b></div><div class="answer-chip">Source<br><b>${esc(b.sourceMode||'offline')}</b></div><div class="answer-chip">Unknowns<br><b>Visible</b></div></div><button class="primary wide" data-action="thesis" data-id="${esc(id)}">${esc(t('thesis'))}</button></div>`,'AI BRIEFING')}
  function openThesis(id){const m=N.matches.find(x=>x.id===id);if(!m)return;openModal(t('thesis'),`<form id="thesisForm" novalidate data-match-id="${esc(id)}"><div class="ai-card"><p><b>${esc(m.home)} — ${esc(m.away)}</b></p>${[['scenario',t('scenario')],['reason',t('reason')],['risk',t('risk')]].map(([name,label])=>`<div class="field"><label for="${name}">${esc(label)}</label><textarea class="textarea" id="${name}" name="${name}" aria-describedby="${name}Error"></textarea><span class="field-error" id="${name}Error"></span></div>`).join('')}<div class="range-row"><label for="confidence">${esc(t('confidence'))}</label><b id="confValue">65%</b></div><input id="confidence" name="confidence" type="range" min="30" max="95" value="65" class="wide"><button class="primary wide" type="submit" data-testid="save-thesis">${esc(t('save'))}</button></div></form>`,'MATCH THESIS')}
  function validateThesis(form){let ok=true;['scenario','reason','risk'].forEach(name=>{const field=form.elements[name],error=$(`#${name}Error`);const valid=field.value.trim().length>=8;field.setAttribute('aria-invalid',String(!valid));error.textContent=valid?'':t('required');if(!valid&&ok){field.focus();ok=false}});return ok}
  function saveThesis(form){if(!validateThesis(form))return;const id=form.dataset.matchId;N.state.thesis={matchId:id,scenario:form.elements.scenario.value.trim(),reason:form.elements.reason.value.trim(),risk:form.elements.risk.value.trim(),confidence:Number(form.elements.confidence.value),locked:true,createdAt:new Date().toISOString()};save();closeModal();renderDynamic();toast(t('saved'))}
  function openMatch(id){const m=N.matches.find(x=>x.id===id);if(m)openModal(`${m.home} — ${m.away}`,matchCard(m),'MATCH INTELLIGENCE')}
  function continueLoop(){const s=stage();if(s==='diagnostic')openModal(t('diagnostic'),`<div class="ai-card" data-testid="diagnostic"><p>Насколько уверенно ты обычно оцениваешь матч до стартовых составов?</p>${[55,70,85].map(v=>`<button class="secondary wide" data-action="diagnostic" data-value="${v}">${v}%</button>`).join('')}</div>`,'STARTING POINT');else if(s==='briefing')openBriefing(featured().id);else if(s==='thesis')openThesis(featured().id);else openReplay()}
  function openReplay(){openModal(t('replay'),`<div class="ai-card" data-testid="replay"><span class="kicker">ORIGINAL DECISION</span><p><b>${esc(N.state.thesis?.scenario||'')}</b></p><p>${esc(N.state.thesis?.reason||'')}</p><span class="kicker">DECLARED RISK</span><p>${esc(N.state.thesis?.risk||'')}</p><div class="answer-grid"><div class="answer-chip">Original confidence<br><b>${N.state.thesis?.confidence||0}%</b></div><div class="answer-chip">Calibration<br><b>${N.state.calibration.score}%</b></div><div class="answer-chip">Decision quality<br><b>Review</b></div></div><button class="primary wide" data-action="complete-replay">Complete Replay</button></div>`,'DECISION REPLAY')}
  async function ask(){const field=$('#aiQuestion'),error=$('#aiError'),q=field.value.trim();if(q.length<4){error.textContent=t('required');field.focus();return}error.textContent='';$('#aiResult').innerHTML='<div class="ai-answer">Analyzing evidence…</div>';const a=await N.ai.ask(q);const text=typeof a==='string'?a:a.answer;$('#aiResult').innerHTML=`<div class="ai-answer"><span class="kicker">CONCLUSION</span><p>${esc(text)}</p><div class="answer-grid"><div class="answer-chip">Confidence<br><b>Medium</b></div><div class="answer-chip">Source<br><b>Offline rules</b></div><div class="answer-chip">Alternative<br><b>Required</b></div></div></div>`}
  function exportData(){const blob=new Blob([N.storage.export()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`noviq-${N.config.version}-backup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast(t('saved'))}
  function importData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{N.storage.import(await file.text());N.state=N.storage.load();renderApp();toast(t('restored'))}catch{toast(t('invalidBackup'))}};input.click()}
  function languageDialog(){openModal(t('language'),`<div class="settings">${[['ru','Русский'],['ua','Українська'],['en','English']].map(([code,label])=>`<button class="setting" data-action="set-language" data-language="${code}"><span>${label}</span><b>${N.state.language===code?icon('check'):''}</b></button>`).join('')}</div>`,'LOCALIZATION')}
  function health(){const report=N.health?.run?.()||{ok:true};openModal(t('health'),`<div class="ai-card"><div class="ai-orb">${icon(report.ok?'check':'heart')}</div><h3>${esc(report.ok?t('healthy'):'Check required')}</h3><div class="evidence"><span>Version ${esc(N.config.version)}</span><span>Storage: local backup active</span><span>Runtime: offline production</span><span>Data: curated demonstration pack</span></div></div>`,'SYSTEM STATUS')}
  function confirmReset(){openModal(t('resetConfirm'),`<div class="ai-card"><p>This removes Thesis, Replay, Sports IQ progress and settings from this device.</p><div class="actions"><button class="secondary" data-action="close">${esc(t('cancel'))}</button><button class="primary" data-action="confirm-reset">${esc(t('confirm'))}</button></div></div>`,'DATA CONTROL')}
  function onboarding(){if(N.state.onboardingSeen)return;document.body.insertAdjacentHTML('beforeend',`<div class="onboarding" role="dialog" aria-modal="true" aria-labelledby="onboardingTitle"><section class="onboarding-card"><span class="kicker">NOVIQ ${esc(N.config.version)}</span><h1 id="onboardingTitle">${esc(t('onboarding'))}</h1><p>${esc(t('onboardingCopy'))}</p><div class="onboarding-list">${[['target','Briefing','Separate facts from unknowns.'],['chart','Thesis','Lock scenario, evidence and risk.'],['check','Replay','Review decision quality, not luck.']].map(([i,title,desc])=>`<div class="onboarding-item"><span class="setting-icon">${icon(i)}</span><div><b>${title}</b><small>${desc}</small></div></div>`).join('')}</div><button class="primary wide" data-action="start" data-testid="start-onboarding">${esc(t('start'))}</button></section></div>`)}
  function trapFocus(e){if(e.key!=='Tab'||!$('#modal').classList.contains('open'))return;const focusable=$$('#modal button,#modal textarea,#modal input').filter(x=>!x.disabled);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
  function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-nav],[data-filter]');if(!el)return;if(el.dataset.nav){show(el.dataset.nav);return}if(el.dataset.filter){matchFilter=el.dataset.filter;$$('.filter-chip').forEach(x=>x.classList.toggle('active',x===el));renderMatches();return}const a=el.dataset.action,id=el.dataset.id;if(a==='theme'){N.state.theme=N.state.theme==='dark'?'light':'dark';save();renderApp()}else if(a==='profile')show('profile');else if(a==='matches')show('matches');else if(a==='close')closeModal();else if(a==='continue')continueLoop();else if(a==='briefing')openBriefing(id);else if(a==='thesis')openThesis(id);else if(a==='match')openMatch(id);else if(a==='ask')ask();else if(a==='diagnostic'){N.state.diagnostic={completed:true,answers:[Number(el.dataset.value)],lastAt:new Date().toISOString()};save();closeModal();renderDynamic();toast(t('saved'))}else if(a==='complete-replay'){N.state.replay={completedAt:new Date().toISOString(),matchId:N.state.thesis?.matchId};N.state.completedLoops+=1;N.state.sportsIQ+=18;N.state.thesis=null;save();closeModal();renderApp();toast(t('replayDone'))}else if(a==='stage'){const target=el.dataset.stage;if(rank[target]<=rank[stage()])target==='replay'?openReplay():target==='thesis'?openThesis(featured().id):target==='briefing'?openBriefing(featured().id):continueLoop()}else if(a==='export')exportData();else if(a==='import')importData();else if(a==='language')languageDialog();else if(a==='set-language'){N.state.language=el.dataset.language;save();closeModal();renderApp()}else if(a==='health')health();else if(a==='reset')confirmReset();else if(a==='confirm-reset'){N.storage.reset();N.state=N.storage.load();closeModal();renderApp()}else if(a==='start'){N.state.onboardingSeen=true;save();$('.onboarding')?.remove();continueLoop()}});
    document.addEventListener('submit',e=>{if(e.target.id==='thesisForm'){e.preventDefault();saveThesis(e.target)}});
    document.addEventListener('input',e=>{if(e.target.id==='confidence')$('#confValue').textContent=`${e.target.value}%`});
    document.addEventListener('keydown',e=>{trapFocus(e);if(e.key==='Escape')closeModal()});
  }
  function renderApp(){document.body.innerHTML=markup();document.documentElement.dataset.theme=N.state.theme;document.documentElement.lang=N.state.language==='ua'?'uk':N.state.language;renderJourney();renderFeatured();renderMatches();show(N.state.activeScreen||'home');onboarding()}
  bind();renderApp();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
})();