import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const read = path => fs.readFileSync(path,'utf8');
const index = read('index.html');
const beta = read('mvp-beta.js');
const css = read('mvp-beta.css');
const sw = read('sw-v52.js');
for (const file of ['about.html','privacy.html','terms.html','mvp-beta.js','mvp-beta.css']) assert.ok(fs.existsSync(file), `missing ${file}`);
new vm.Script(beta,{filename:'mvp-beta.js'});
assert.ok(index.includes('mvp-beta.css') && index.includes('mvp-beta.js'));
assert.ok(index.includes('NOVIQ 6 MVP'));
assert.ok(beta.includes('noviq-mvp-feedback') && beta.includes('beta_feedback_saved'));
assert.ok(beta.includes('Briefing → Thesis → Replay'));
assert.ok(beta.includes("dialog.showModal()") && beta.includes("type=\"submit\""));
assert.ok(css.includes('.mvp-mission') && css.includes('.mvp-dialog'));
for (const asset of ['mvp-beta.js','mvp-beta.css','about.html','privacy.html','terms.html']) assert.ok(sw.includes(`./${asset}`), `${asset} missing from offline cache`);
assert.ok(read('privacy.html').includes('does not send telemetry'));
assert.ok(read('terms.html').includes('No betting guarantee'));
console.log('NOVIQ MVP beta gates passed.');
