import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html'),sw=read('sw.js'),bootstrap=read('bootstrap-v5.js'),app=read('app-v5.js'),services=read('services.js');
const manifest=JSON.parse(read('manifest.webmanifest'));
const scripts=[...index.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]);
const styles=[...index.matchAll(/<link[^>]+href="([^"]+\.css)"/g)].map(m=>m[1]);
assert.ok(index.includes('NOVIQ 5'),'index must identify NOVIQ 5');
assert.deepEqual(scripts,['runtime-config.js','config.js','bootstrap-v5.js','data.js','services.js','app-v5.js']);
assert.deepEqual(styles,['styles-v5.css']);
assert.ok(manifest.name.includes('NOVIQ 5'));
for(const asset of[...scripts,...styles,'manifest.webmanifest','icon.svg'])assert.ok(fs.existsSync(asset),`missing ${asset}`);
for(const script of scripts){new vm.Script(read(script),{filename:script});assert.ok(sw.includes(`'./${script}'`),`${script} missing from cache`)}
assert.ok(bootstrap.includes("version='5.0.0'")&&bootstrap.includes('noviq-v4.1-state'),'version and migration missing');
assert.ok(app.includes('MATCH THESIS')&&app.includes('DECISION REPLAY')&&app.includes('AI BRIEFING'),'core loop missing');
assert.ok(app.includes('N.storage.export')&&app.includes('N.storage.import'),'data controls missing');
assert.ok(app.includes('N.health.run'),'health check missing');
assert.ok(services.includes('INVALID_NOVIQ_BACKUP'),'validated backups missing');
assert.ok(sw.includes("request.mode==='navigate'"),'navigation fallback missing');
assert.ok(!index.includes('styles-world.css')&&!index.includes('ui-part-1.js'),'legacy UI must not load');
console.log(`NOVIQ 5 checks passed: ${scripts.length} scripts, ${styles.length} stylesheet.`);