import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(path,'utf8');
const index=read('index.html'),core=read('core-v52.js'),platform=read('platform-v6.js'),app=read('app-v52.js'),a11y=read('a11y-v52.js'),styles=read('styles-v52.css'),sw=read('sw-v52.js'),auth=read('auth-client.js'),api=read('api-client.js'),prelaunch=read('prelaunch-v61.js'),headers=read('_headers');
const manifest=JSON.parse(read('manifest.webmanifest'));
const scripts=[...index.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]);
const stylesheets=[...index.matchAll(/<link[^>]+href="([^"]+\.css)"/g)].map(m=>m[1]);
assert.deepEqual(scripts,['polyfills-v52.js','runtime-config.js','auth-client.js','api-client.js','data.js','core-v52.js','platform-v6.js','app-v52.js','a11y-v52.js','mvp-beta.js','prelaunch-v61.js']);
assert.deepEqual(stylesheets,['styles-v52.css','mvp-beta.css','prelaunch-v61.css']);
assert.ok(index.includes('NOVIQ 6.1')&&manifest.name.includes('6.1'));
for(const asset of [...scripts,...stylesheets,'manifest.webmanifest','icon.svg'])assert.ok(fs.existsSync(asset),`missing ${asset}`);
for(const script of scripts)new vm.Script(read(script),{filename:script});
for(const script of scripts.filter(x=>x!=='runtime-config.js'))assert.ok(sw.includes(`'./${script}'`),`${script} missing from offline cache`);
assert.ok(!sw.includes("'./runtime-config.js'"),'runtime config must never be precached');
assert.ok(sw.includes("pathname.startsWith('/v1/')")&&sw.includes("pathname==='/runtime-config.js'"),'network-only auth/API policy missing');
assert.ok(core.includes('schemaVersion:7')||core.includes('schemaVersion: 7'));
assert.ok(core.includes("throw new Error('REPLAY_EXISTS')")&&core.includes('scoreReplay('));
assert.ok(platform.includes("version:'6.1.0'")&&platform.includes('cloudIdentity:true')&&platform.includes('cloudSync:true'));
assert.ok(app.includes('data-testid="save-thesis"')&&app.includes('data-testid="replay"')&&!app.includes('alert(')&&!app.includes('confirm('));
assert.ok(a11y.includes("child.setAttribute('inert'"));
assert.ok(styles.includes('prefers-reduced-motion')&&styles.includes(':focus-visible'));
assert.ok(auth.includes('signIn(email, password)')&&auth.includes('signUp(email, password')&&auth.includes("request('/recover'")&&auth.includes('refresh(force = false)'));
assert.ok(!auth.includes('password } })); localStorage'),'password must never be stored');
assert.ok(api.includes("bootstrap(){")&&api.includes('updateProfile(profile)')&&api.includes('deleteMyData()')&&api.includes('sync(payload)'));
for(const token of ['identity-gate','syncPayload()','Sports Memory','data-prelaunch-edit','deleteCloudData'])assert.ok(prelaunch.includes(token),`prelaunch missing ${token}`);
assert.ok(headers.includes("connect-src 'self' https://*.supabase.co")&&!headers.includes("connect-src 'self' https: wss:"));
assert.ok(headers.includes('Strict-Transport-Security'));
assert.ok(sw.includes("const VERSION='6.1.0'"));
console.log('NOVIQ 6.1 prelaunch structural checks passed.');
