import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const read = path => fs.readFileSync(path, 'utf8');
const index = read('index.html');
const core = read('core-v52.js');
const platform = read('platform-v6.js');
const app = read('app-v52.js');
const a11y = read('a11y-v52.js');
const styles = read('styles-v52.css');
const sw = read('sw-v52.js');
const manifest = JSON.parse(read('manifest.webmanifest'));
const scripts = [...index.matchAll(/<script src="([^"]+)"/g)].map(match => match[1]);
const stylesheets = [...index.matchAll(/<link[^>]+href="([^"]+\.css)"/g)].map(match => match[1]);

assert.deepEqual(scripts, ['polyfills-v52.js','data.js','core-v52.js','platform-v6.js','app-v52.js','a11y-v52.js']);
assert.deepEqual(stylesheets, ['styles-v52.css']);
assert.ok(index.includes('NOVIQ 6'));
assert.ok(manifest.name.includes('6'));
for (const asset of [...scripts, ...stylesheets, 'manifest.webmanifest', 'icon.svg']) assert.ok(fs.existsSync(asset), `missing ${asset}`);
for (const script of scripts) new vm.Script(read(script), { filename: script });
for (const script of scripts) assert.ok(sw.includes(`'./${script}'`), `${script} missing from offline cache`);

assert.ok(core.includes('schemaVersion:7') || core.includes('schemaVersion: 7'));
assert.ok(core.includes('saved.onboarding?.completed'), '5.0 onboarding migration missing');
assert.ok(core.includes('theses:[]') && core.includes('replays:[]') && core.includes('completedReplayIds:[]'));
assert.ok(core.includes("throw new Error('REPLAY_EXISTS')"), 'Replay idempotency missing');
assert.ok(core.includes('scoreReplay(') && core.includes('breakdown'), 'Sports IQ scoring missing');
assert.ok(core.includes('inspect(raw)') && core.includes('summary:'), 'import preview missing');
assert.ok(platform.includes("version:'6.0.0'"), 'NOVIQ 6 release metadata missing');
assert.ok(platform.includes('localTelemetry:true') && platform.includes('crashRecovery:true'), 'platform flags missing');
assert.ok(platform.includes('capture(error') && platform.includes('track(name'), 'telemetry/crash APIs missing');
assert.ok(app.includes('data-testid="save-thesis"') && app.includes('data-testid="replay"'));
assert.ok(app.includes('pendingImport') && app.includes('confirm-import'));
assert.ok(app.includes('controllerchange') && app.includes('updateBar'));
assert.ok(!app.includes('alert(') && !app.includes('confirm('));
assert.ok(a11y.includes("child.setAttribute('inert'"), 'sibling inert management missing');
assert.ok(styles.includes('prefers-reduced-motion') && styles.includes(':focus-visible'));
assert.ok(styles.split('\n').length > 100, 'source CSS must remain formatted');
assert.ok(sw.includes("const VERSION='6.0.0'"));
assert.ok(sw.includes('Optional asset failed'));
assert.ok(sw.includes("request.mode==='navigate'"));
assert.ok(!index.includes('app-v5.js') && !index.includes('styles-v5.css'));
console.log('NOVIQ 6 structural checks passed.');
